# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouDouVideo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouDouVideo
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SBJson', '~> 5.0.0'
  pod 'RongCloudIM', '~> 2.10.6'
  pod 'RongCloudRTC', '~> 2.10.6'
  
  pod 'CustomIOSAlertView', '~> 0.9.5'
  pod 'DQAlertView', '~> 1.3.0'
  
  pod 'MBProgressHUD', '~> 1.2.0'
end
