# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SmallVideoSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmallVideoSwift
  pod 'SnapKit', '~> 5.0.1'
  pod 'Alamofire', '~> 5.2.2'
end
